### ISSUE TITLE
Unable to open Project

### ISSUE THREAD

**Issue by SteamDosh** [BrannigansLaw/Skyrim-Behavior-Editor-#5]
Been getting this error, I've used this tool to extract the .bsa https://www.nexusmods.com/skyrimspecialedition/mods/974/

![image](https://user-images.githubusercontent.com/5054096/42517789-ea557614-84a3-11e8-842d-f3f42ccfa210.png)

**Comment by SteamDosh** [comment]
Additionally upon closing it deleted every file except for those in directory 

- /_1stperson
- /animations

**Comment by Zartar** [comment]
Thanks for the report, did you try to open the project using the "Open Packed Project" option? I'm adding more descriptive error messages for similar issues but I only see that message when attempting to open a packed project using the "Open Unpacked Project" or if the file itself is corrupted.
